# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: ml #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: ops
  location: northeurope
  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: true


  # Azure DevOps
  ado_service_connection_rg: sc-subscription-level
  ado_service_connection_aml_ws: sc-subscription-level

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)$(postfix)-$(environment)
  aml_workspace: aml-$(namespace)$(postfix)-$(environment)
  application_insights: aml-$(namespace)$(postfix)-$(environment)
  key_vault: aml-kv-$(namespace)$(postfix)-$(environment)
  container_registry: amlacr$(namespace)$(postfix)$(environment)
  storage_account: amlst$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: rg-$(namespace)-$(postfix)-$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
